### ISSUE TITLE
Structures removal

### ISSUE THREAD

**Issue by TLiG98** [MaxenceDC/sparsestructures#30] opened 2024-07-01 18:04 UTC
Blacklist a certain, or multiple structures from being generated.

could be like this in the config file:

**Comment by TLiG98** [comment] 2024-07-01 18:13
![IMG_7927](https://github.com/MaxenceDC/sparsestructures/assets/26041401/ca3f2b05-0954-478a-ab8c-00db85e2d534)

**Comment by MaxenceDC** [comment] 2024-07-01 18:34
This is planned (but not as easy to implement).
Will let you know when this is available

**Comment by MaxenceDC** [comment] 2024-07-01 18:34
Duplicate of #15 btw

**Closed as not planned by MaxenceDC** 2024-07-01 18:34 UTC
Labels: duplicate
